#!/bin/bash

#setup screenshot folder in pictures
mkdir /Users/rhartshorn/Pictures/Screenshots
#setup location for profile pics
mkdir /Users/rhartshorn/Pictures/ProfileImages

#setup folder to hold power points
mkdir /Users/rhartshorn/Documents/PowerPoint
#setup main github location
mkdir /Users/rhartshorn/Documents/Github
#setup test environment
mkdir /Users/rhartshorn/Documents/TestProjects

